name: Phoenix Test Automation Workflow

on:
  push:
    branches: [ "feature/r9-data-driven-faker" ]
  pull_request:
    branches: [ "feature/r9-data-driven-faker" ]
  schedule: #set the cron for midnight IST
    - cron: "30 18 * * *"
    - cron: "30 17 * * *"
    - cron: "30 16 * * *"
  workflow_dispatch: 
    inputs:
      env:
        description: "Enviroment"
        type: choice
        options: [dev,qa,uat]
        default: qa
        required: true
        
      suiteXmlFile:
        description: "TestNg XML File"
        type: choice
        options: [testng.xml,smoke.xml,regression.xml,testng-datadriven.xml]
        default: qa
        required: true

      groups:
        description: "Groups"
        type: choice
        options: [csv,faker,smoke,regression,sanity]
        default: faker
        required: true
        

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Default Values for Executions
      id: default
      run: |
            echo "suiteXmlFile=${{ github.event.inputs.suiteXmlFile || 'testng.xml'}}" >> $GITHUB_OUTPUT
            echo "env=${{ github.event.inputs.env || 'qa'}}" >> $GITHUB_OUTPUT
            echo "groups=${{ github.event.inputs.groups || 'faker'}}" >> $GITHUB_OUTPUT
        
    - name: Execute Test Automation Framework
      run: mvn clean test -DsuiteXmlFile="${{ steps.default.outputs.suiteXmlFile }}" -Denv="${{ steps.default.outputs.env }}" -Dgroups="${{ steps.default.outputs.faker }}"

    - name: Upload A Build Artifact
      if: always()
      uses: actions/upload-artifact@v7.0.0
      with:
        name: Surefire Reports
        path: target/surefire-reports/
        retention-days: 30
      
     
     
      
